/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrrjRouteImport } from './routes/urrj'
import { Route as UdpRouteImport } from './routes/udp'
import { Route as UcpRouteImport } from './routes/ucp'
import { Route as UcmRouteImport } from './routes/ucm'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ExpedienteRouteImport } from './routes/expediente'
import { Route as ExhortosRouteImport } from './routes/exhortos'
import { Route as DictamenIaRouteImport } from './routes/dictamen-ia'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ConectoresRouteImport } from './routes/conectores'
import { Route as BoletinesRouteImport } from './routes/boletines'
import { Route as AmparosRouteImport } from './routes/amparos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as ContratosIndexRouteImport } from './routes/contratos.index'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as ContratosEditorRouteImport } from './routes/contratos.editor'

const UrrjRoute = UrrjRouteImport.update({
  id: '/urrj',
  path: '/urrj',
  getParentRoute: () => rootRouteImport,
} as any)
const UdpRoute = UdpRouteImport.update({
  id: '/udp',
  path: '/udp',
  getParentRoute: () => rootRouteImport,
} as any)
const UcpRoute = UcpRouteImport.update({
  id: '/ucp',
  path: '/ucp',
  getParentRoute: () => rootRouteImport,
} as any)
const UcmRoute = UcmRouteImport.update({
  id: '/ucm',
  path: '/ucm',
  getParentRoute: () => rootRouteImport,
} as any)
const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedienteRoute = ExpedienteRouteImport.update({
  id: '/expediente',
  path: '/expediente',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhortosRoute = ExhortosRouteImport.update({
  id: '/exhortos',
  path: '/exhortos',
  getParentRoute: () => rootRouteImport,
} as any)
const DictamenIaRoute = DictamenIaRouteImport.update({
  id: '/dictamen-ia',
  path: '/dictamen-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectoresRoute = ConectoresRouteImport.update({
  id: '/conectores',
  path: '/conectores',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletinesRoute = BoletinesRouteImport.update({
  id: '/boletines',
  path: '/boletines',
  getParentRoute: () => rootRouteImport,
} as any)
const AmparosRoute = AmparosRouteImport.update({
  id: '/amparos',
  path: '/amparos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosIndexRoute = ContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosEditorRoute = ContratosEditorRouteImport.update({
  id: '/contratos/editor',
  path: '/contratos/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucp': typeof UcpRoute
  '/udp': typeof UdpRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos/': typeof ContratosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucp': typeof UcpRoute
  '/udp': typeof UdpRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos': typeof ContratosIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucp': typeof UcpRoute
  '/udp': typeof UdpRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos/': typeof ContratosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amparos'
    | '/boletines'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/exhortos'
    | '/expediente'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucp'
    | '/udp'
    | '/urrj'
    | '/contratos/editor'
    | '/expedientes/$id'
    | '/contratos/'
    | '/expedientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amparos'
    | '/boletines'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/exhortos'
    | '/expediente'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucp'
    | '/udp'
    | '/urrj'
    | '/contratos/editor'
    | '/expedientes/$id'
    | '/contratos'
    | '/expedientes'
  id:
    | '__root__'
    | '/'
    | '/amparos'
    | '/boletines'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/exhortos'
    | '/expediente'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucp'
    | '/udp'
    | '/urrj'
    | '/contratos/editor'
    | '/expedientes/$id'
    | '/contratos/'
    | '/expedientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmparosRoute: typeof AmparosRoute
  BoletinesRoute: typeof BoletinesRoute
  ConectoresRoute: typeof ConectoresRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DictamenIaRoute: typeof DictamenIaRoute
  ExhortosRoute: typeof ExhortosRoute
  ExpedienteRoute: typeof ExpedienteRoute
  RecursosRoute: typeof RecursosRoute
  TramitesRoute: typeof TramitesRoute
  UcmRoute: typeof UcmRoute
  UcpRoute: typeof UcpRoute
  UdpRoute: typeof UdpRoute
  UrrjRoute: typeof UrrjRoute
  ContratosEditorRoute: typeof ContratosEditorRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  ContratosIndexRoute: typeof ContratosIndexRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urrj': {
      id: '/urrj'
      path: '/urrj'
      fullPath: '/urrj'
      preLoaderRoute: typeof UrrjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udp': {
      id: '/udp'
      path: '/udp'
      fullPath: '/udp'
      preLoaderRoute: typeof UdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucp': {
      id: '/ucp'
      path: '/ucp'
      fullPath: '/ucp'
      preLoaderRoute: typeof UcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucm': {
      id: '/ucm'
      path: '/ucm'
      fullPath: '/ucm'
      preLoaderRoute: typeof UcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediente': {
      id: '/expediente'
      path: '/expediente'
      fullPath: '/expediente'
      preLoaderRoute: typeof ExpedienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhortos': {
      id: '/exhortos'
      path: '/exhortos'
      fullPath: '/exhortos'
      preLoaderRoute: typeof ExhortosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictamen-ia': {
      id: '/dictamen-ia'
      path: '/dictamen-ia'
      fullPath: '/dictamen-ia'
      preLoaderRoute: typeof DictamenIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectores': {
      id: '/conectores'
      path: '/conectores'
      fullPath: '/conectores'
      preLoaderRoute: typeof ConectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletines': {
      id: '/boletines'
      path: '/boletines'
      fullPath: '/boletines'
      preLoaderRoute: typeof BoletinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amparos': {
      id: '/amparos'
      path: '/amparos'
      fullPath: '/amparos'
      preLoaderRoute: typeof AmparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/': {
      id: '/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof ContratosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/editor': {
      id: '/contratos/editor'
      path: '/contratos/editor'
      fullPath: '/contratos/editor'
      preLoaderRoute: typeof ContratosEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmparosRoute: AmparosRoute,
  BoletinesRoute: BoletinesRoute,
  ConectoresRoute: ConectoresRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DictamenIaRoute: DictamenIaRoute,
  ExhortosRoute: ExhortosRoute,
  ExpedienteRoute: ExpedienteRoute,
  RecursosRoute: RecursosRoute,
  TramitesRoute: TramitesRoute,
  UcmRoute: UcmRoute,
  UcpRoute: UcpRoute,
  UdpRoute: UdpRoute,
  UrrjRoute: UrrjRoute,
  ContratosEditorRoute: ContratosEditorRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  ContratosIndexRoute: ContratosIndexRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
