/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrrjRouteImport } from './routes/urrj'
import { Route as UfcFichaRouteImport } from './routes/ufc-ficha'
import { Route as UfcRouteImport } from './routes/ufc'
import { Route as UdpRouteImport } from './routes/udp'
import { Route as UcpFichaRouteImport } from './routes/ucp-ficha'
import { Route as UcpRouteImport } from './routes/ucp'
import { Route as UcmFichaRouteImport } from './routes/ucm-ficha'
import { Route as UcmRouteImport } from './routes/ucm'
import { Route as TramitesRouteImport } from './routes/tramites'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as LiquidacionRouteImport } from './routes/liquidacion'
import { Route as JufaRouteImport } from './routes/jufa'
import { Route as FirmarRouteImport } from './routes/firmar'
import { Route as ExpedienteRouteImport } from './routes/expediente'
import { Route as ExhortosRouteImport } from './routes/exhortos'
import { Route as DireccionRouteImport } from './routes/direccion'
import { Route as DictamenIaRouteImport } from './routes/dictamen-ia'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ConectoresRouteImport } from './routes/conectores'
import { Route as ComparadorClientesRouteImport } from './routes/comparador-clientes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BoletinesRouteImport } from './routes/boletines'
import { Route as AmparosRouteImport } from './routes/amparos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpedientesIndexRouteImport } from './routes/expedientes.index'
import { Route as EscritosIndexRouteImport } from './routes/escritos.index'
import { Route as ContratosIndexRouteImport } from './routes/contratos.index'
import { Route as ExpedientesIdRouteImport } from './routes/expedientes.$id'
import { Route as EscritosNuevaRouteImport } from './routes/escritos.nueva'
import { Route as EscritosEditorRouteImport } from './routes/escritos.editor'
import { Route as ContratosNuevaRouteImport } from './routes/contratos.nueva'
import { Route as ContratosEditorRouteImport } from './routes/contratos.editor'

const UrrjRoute = UrrjRouteImport.update({
  id: '/urrj',
  path: '/urrj',
  getParentRoute: () => rootRouteImport,
} as any)
const UfcFichaRoute = UfcFichaRouteImport.update({
  id: '/ufc-ficha',
  path: '/ufc-ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const UfcRoute = UfcRouteImport.update({
  id: '/ufc',
  path: '/ufc',
  getParentRoute: () => rootRouteImport,
} as any)
const UdpRoute = UdpRouteImport.update({
  id: '/udp',
  path: '/udp',
  getParentRoute: () => rootRouteImport,
} as any)
const UcpFichaRoute = UcpFichaRouteImport.update({
  id: '/ucp-ficha',
  path: '/ucp-ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const UcpRoute = UcpRouteImport.update({
  id: '/ucp',
  path: '/ucp',
  getParentRoute: () => rootRouteImport,
} as any)
const UcmFichaRoute = UcmFichaRouteImport.update({
  id: '/ucm-ficha',
  path: '/ucm-ficha',
  getParentRoute: () => rootRouteImport,
} as any)
const UcmRoute = UcmRouteImport.update({
  id: '/ucm',
  path: '/ucm',
  getParentRoute: () => rootRouteImport,
} as any)
const TramitesRoute = TramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidacionRoute = LiquidacionRouteImport.update({
  id: '/liquidacion',
  path: '/liquidacion',
  getParentRoute: () => rootRouteImport,
} as any)
const JufaRoute = JufaRouteImport.update({
  id: '/jufa',
  path: '/jufa',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmarRoute = FirmarRouteImport.update({
  id: '/firmar',
  path: '/firmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedienteRoute = ExpedienteRouteImport.update({
  id: '/expediente',
  path: '/expediente',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhortosRoute = ExhortosRouteImport.update({
  id: '/exhortos',
  path: '/exhortos',
  getParentRoute: () => rootRouteImport,
} as any)
const DireccionRoute = DireccionRouteImport.update({
  id: '/direccion',
  path: '/direccion',
  getParentRoute: () => rootRouteImport,
} as any)
const DictamenIaRoute = DictamenIaRouteImport.update({
  id: '/dictamen-ia',
  path: '/dictamen-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectoresRoute = ConectoresRouteImport.update({
  id: '/conectores',
  path: '/conectores',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorClientesRoute = ComparadorClientesRouteImport.update({
  id: '/comparador-clientes',
  path: '/comparador-clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletinesRoute = BoletinesRouteImport.update({
  id: '/boletines',
  path: '/boletines',
  getParentRoute: () => rootRouteImport,
} as any)
const AmparosRoute = AmparosRouteImport.update({
  id: '/amparos',
  path: '/amparos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIndexRoute = ExpedientesIndexRouteImport.update({
  id: '/expedientes/',
  path: '/expedientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritosIndexRoute = EscritosIndexRouteImport.update({
  id: '/escritos/',
  path: '/escritos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosIndexRoute = ContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesIdRoute = ExpedientesIdRouteImport.update({
  id: '/expedientes/$id',
  path: '/expedientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritosNuevaRoute = EscritosNuevaRouteImport.update({
  id: '/escritos/nueva',
  path: '/escritos/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritosEditorRoute = EscritosEditorRouteImport.update({
  id: '/escritos/editor',
  path: '/escritos/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosNuevaRoute = ContratosNuevaRouteImport.update({
  id: '/contratos/nueva',
  path: '/contratos/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosEditorRoute = ContratosEditorRouteImport.update({
  id: '/contratos/editor',
  path: '/contratos/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/calendario': typeof CalendarioRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/comparador-clientes': typeof ComparadorClientesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/direccion': typeof DireccionRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/firmar': typeof FirmarRoute
  '/jufa': typeof JufaRoute
  '/liquidacion': typeof LiquidacionRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucm-ficha': typeof UcmFichaRoute
  '/ucp': typeof UcpRoute
  '/ucp-ficha': typeof UcpFichaRoute
  '/udp': typeof UdpRoute
  '/ufc': typeof UfcRoute
  '/ufc-ficha': typeof UfcFichaRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/contratos/nueva': typeof ContratosNuevaRoute
  '/escritos/editor': typeof EscritosEditorRoute
  '/escritos/nueva': typeof EscritosNuevaRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos/': typeof ContratosIndexRoute
  '/escritos/': typeof EscritosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/calendario': typeof CalendarioRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/comparador-clientes': typeof ComparadorClientesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/direccion': typeof DireccionRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/firmar': typeof FirmarRoute
  '/jufa': typeof JufaRoute
  '/liquidacion': typeof LiquidacionRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucm-ficha': typeof UcmFichaRoute
  '/ucp': typeof UcpRoute
  '/ucp-ficha': typeof UcpFichaRoute
  '/udp': typeof UdpRoute
  '/ufc': typeof UfcRoute
  '/ufc-ficha': typeof UfcFichaRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/contratos/nueva': typeof ContratosNuevaRoute
  '/escritos/editor': typeof EscritosEditorRoute
  '/escritos/nueva': typeof EscritosNuevaRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos': typeof ContratosIndexRoute
  '/escritos': typeof EscritosIndexRoute
  '/expedientes': typeof ExpedientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amparos': typeof AmparosRoute
  '/boletines': typeof BoletinesRoute
  '/calendario': typeof CalendarioRoute
  '/cliente': typeof ClienteRoute
  '/clientes': typeof ClientesRoute
  '/comparador-clientes': typeof ComparadorClientesRoute
  '/conectores': typeof ConectoresRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dictamen-ia': typeof DictamenIaRoute
  '/direccion': typeof DireccionRoute
  '/exhortos': typeof ExhortosRoute
  '/expediente': typeof ExpedienteRoute
  '/firmar': typeof FirmarRoute
  '/jufa': typeof JufaRoute
  '/liquidacion': typeof LiquidacionRoute
  '/recursos': typeof RecursosRoute
  '/tramites': typeof TramitesRoute
  '/ucm': typeof UcmRoute
  '/ucm-ficha': typeof UcmFichaRoute
  '/ucp': typeof UcpRoute
  '/ucp-ficha': typeof UcpFichaRoute
  '/udp': typeof UdpRoute
  '/ufc': typeof UfcRoute
  '/ufc-ficha': typeof UfcFichaRoute
  '/urrj': typeof UrrjRoute
  '/contratos/editor': typeof ContratosEditorRoute
  '/contratos/nueva': typeof ContratosNuevaRoute
  '/escritos/editor': typeof EscritosEditorRoute
  '/escritos/nueva': typeof EscritosNuevaRoute
  '/expedientes/$id': typeof ExpedientesIdRoute
  '/contratos/': typeof ContratosIndexRoute
  '/escritos/': typeof EscritosIndexRoute
  '/expedientes/': typeof ExpedientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amparos'
    | '/boletines'
    | '/calendario'
    | '/cliente'
    | '/clientes'
    | '/comparador-clientes'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/direccion'
    | '/exhortos'
    | '/expediente'
    | '/firmar'
    | '/jufa'
    | '/liquidacion'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucm-ficha'
    | '/ucp'
    | '/ucp-ficha'
    | '/udp'
    | '/ufc'
    | '/ufc-ficha'
    | '/urrj'
    | '/contratos/editor'
    | '/contratos/nueva'
    | '/escritos/editor'
    | '/escritos/nueva'
    | '/expedientes/$id'
    | '/contratos/'
    | '/escritos/'
    | '/expedientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/amparos'
    | '/boletines'
    | '/calendario'
    | '/cliente'
    | '/clientes'
    | '/comparador-clientes'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/direccion'
    | '/exhortos'
    | '/expediente'
    | '/firmar'
    | '/jufa'
    | '/liquidacion'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucm-ficha'
    | '/ucp'
    | '/ucp-ficha'
    | '/udp'
    | '/ufc'
    | '/ufc-ficha'
    | '/urrj'
    | '/contratos/editor'
    | '/contratos/nueva'
    | '/escritos/editor'
    | '/escritos/nueva'
    | '/expedientes/$id'
    | '/contratos'
    | '/escritos'
    | '/expedientes'
  id:
    | '__root__'
    | '/'
    | '/amparos'
    | '/boletines'
    | '/calendario'
    | '/cliente'
    | '/clientes'
    | '/comparador-clientes'
    | '/conectores'
    | '/configuracion'
    | '/dictamen-ia'
    | '/direccion'
    | '/exhortos'
    | '/expediente'
    | '/firmar'
    | '/jufa'
    | '/liquidacion'
    | '/recursos'
    | '/tramites'
    | '/ucm'
    | '/ucm-ficha'
    | '/ucp'
    | '/ucp-ficha'
    | '/udp'
    | '/ufc'
    | '/ufc-ficha'
    | '/urrj'
    | '/contratos/editor'
    | '/contratos/nueva'
    | '/escritos/editor'
    | '/escritos/nueva'
    | '/expedientes/$id'
    | '/contratos/'
    | '/escritos/'
    | '/expedientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmparosRoute: typeof AmparosRoute
  BoletinesRoute: typeof BoletinesRoute
  CalendarioRoute: typeof CalendarioRoute
  ClienteRoute: typeof ClienteRoute
  ClientesRoute: typeof ClientesRoute
  ComparadorClientesRoute: typeof ComparadorClientesRoute
  ConectoresRoute: typeof ConectoresRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DictamenIaRoute: typeof DictamenIaRoute
  DireccionRoute: typeof DireccionRoute
  ExhortosRoute: typeof ExhortosRoute
  ExpedienteRoute: typeof ExpedienteRoute
  FirmarRoute: typeof FirmarRoute
  JufaRoute: typeof JufaRoute
  LiquidacionRoute: typeof LiquidacionRoute
  RecursosRoute: typeof RecursosRoute
  TramitesRoute: typeof TramitesRoute
  UcmRoute: typeof UcmRoute
  UcmFichaRoute: typeof UcmFichaRoute
  UcpRoute: typeof UcpRoute
  UcpFichaRoute: typeof UcpFichaRoute
  UdpRoute: typeof UdpRoute
  UfcRoute: typeof UfcRoute
  UfcFichaRoute: typeof UfcFichaRoute
  UrrjRoute: typeof UrrjRoute
  ContratosEditorRoute: typeof ContratosEditorRoute
  ContratosNuevaRoute: typeof ContratosNuevaRoute
  EscritosEditorRoute: typeof EscritosEditorRoute
  EscritosNuevaRoute: typeof EscritosNuevaRoute
  ExpedientesIdRoute: typeof ExpedientesIdRoute
  ContratosIndexRoute: typeof ContratosIndexRoute
  EscritosIndexRoute: typeof EscritosIndexRoute
  ExpedientesIndexRoute: typeof ExpedientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urrj': {
      id: '/urrj'
      path: '/urrj'
      fullPath: '/urrj'
      preLoaderRoute: typeof UrrjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ufc-ficha': {
      id: '/ufc-ficha'
      path: '/ufc-ficha'
      fullPath: '/ufc-ficha'
      preLoaderRoute: typeof UfcFichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ufc': {
      id: '/ufc'
      path: '/ufc'
      fullPath: '/ufc'
      preLoaderRoute: typeof UfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udp': {
      id: '/udp'
      path: '/udp'
      fullPath: '/udp'
      preLoaderRoute: typeof UdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucp-ficha': {
      id: '/ucp-ficha'
      path: '/ucp-ficha'
      fullPath: '/ucp-ficha'
      preLoaderRoute: typeof UcpFichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucp': {
      id: '/ucp'
      path: '/ucp'
      fullPath: '/ucp'
      preLoaderRoute: typeof UcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucm-ficha': {
      id: '/ucm-ficha'
      path: '/ucm-ficha'
      fullPath: '/ucm-ficha'
      preLoaderRoute: typeof UcmFichaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ucm': {
      id: '/ucm'
      path: '/ucm'
      fullPath: '/ucm'
      preLoaderRoute: typeof UcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tramites': {
      id: '/tramites'
      path: '/tramites'
      fullPath: '/tramites'
      preLoaderRoute: typeof TramitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidacion': {
      id: '/liquidacion'
      path: '/liquidacion'
      fullPath: '/liquidacion'
      preLoaderRoute: typeof LiquidacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jufa': {
      id: '/jufa'
      path: '/jufa'
      fullPath: '/jufa'
      preLoaderRoute: typeof JufaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmar': {
      id: '/firmar'
      path: '/firmar'
      fullPath: '/firmar'
      preLoaderRoute: typeof FirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediente': {
      id: '/expediente'
      path: '/expediente'
      fullPath: '/expediente'
      preLoaderRoute: typeof ExpedienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhortos': {
      id: '/exhortos'
      path: '/exhortos'
      fullPath: '/exhortos'
      preLoaderRoute: typeof ExhortosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direccion': {
      id: '/direccion'
      path: '/direccion'
      fullPath: '/direccion'
      preLoaderRoute: typeof DireccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictamen-ia': {
      id: '/dictamen-ia'
      path: '/dictamen-ia'
      fullPath: '/dictamen-ia'
      preLoaderRoute: typeof DictamenIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectores': {
      id: '/conectores'
      path: '/conectores'
      fullPath: '/conectores'
      preLoaderRoute: typeof ConectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador-clientes': {
      id: '/comparador-clientes'
      path: '/comparador-clientes'
      fullPath: '/comparador-clientes'
      preLoaderRoute: typeof ComparadorClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletines': {
      id: '/boletines'
      path: '/boletines'
      fullPath: '/boletines'
      preLoaderRoute: typeof BoletinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amparos': {
      id: '/amparos'
      path: '/amparos'
      fullPath: '/amparos'
      preLoaderRoute: typeof AmparosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/': {
      id: '/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof ExpedientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritos/': {
      id: '/escritos/'
      path: '/escritos'
      fullPath: '/escritos/'
      preLoaderRoute: typeof EscritosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/': {
      id: '/contratos/'
      path: '/contratos'
      fullPath: '/contratos/'
      preLoaderRoute: typeof ContratosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes/$id': {
      id: '/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof ExpedientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritos/nueva': {
      id: '/escritos/nueva'
      path: '/escritos/nueva'
      fullPath: '/escritos/nueva'
      preLoaderRoute: typeof EscritosNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritos/editor': {
      id: '/escritos/editor'
      path: '/escritos/editor'
      fullPath: '/escritos/editor'
      preLoaderRoute: typeof EscritosEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/nueva': {
      id: '/contratos/nueva'
      path: '/contratos/nueva'
      fullPath: '/contratos/nueva'
      preLoaderRoute: typeof ContratosNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/editor': {
      id: '/contratos/editor'
      path: '/contratos/editor'
      fullPath: '/contratos/editor'
      preLoaderRoute: typeof ContratosEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmparosRoute: AmparosRoute,
  BoletinesRoute: BoletinesRoute,
  CalendarioRoute: CalendarioRoute,
  ClienteRoute: ClienteRoute,
  ClientesRoute: ClientesRoute,
  ComparadorClientesRoute: ComparadorClientesRoute,
  ConectoresRoute: ConectoresRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DictamenIaRoute: DictamenIaRoute,
  DireccionRoute: DireccionRoute,
  ExhortosRoute: ExhortosRoute,
  ExpedienteRoute: ExpedienteRoute,
  FirmarRoute: FirmarRoute,
  JufaRoute: JufaRoute,
  LiquidacionRoute: LiquidacionRoute,
  RecursosRoute: RecursosRoute,
  TramitesRoute: TramitesRoute,
  UcmRoute: UcmRoute,
  UcmFichaRoute: UcmFichaRoute,
  UcpRoute: UcpRoute,
  UcpFichaRoute: UcpFichaRoute,
  UdpRoute: UdpRoute,
  UfcRoute: UfcRoute,
  UfcFichaRoute: UfcFichaRoute,
  UrrjRoute: UrrjRoute,
  ContratosEditorRoute: ContratosEditorRoute,
  ContratosNuevaRoute: ContratosNuevaRoute,
  EscritosEditorRoute: EscritosEditorRoute,
  EscritosNuevaRoute: EscritosNuevaRoute,
  ExpedientesIdRoute: ExpedientesIdRoute,
  ContratosIndexRoute: ContratosIndexRoute,
  EscritosIndexRoute: EscritosIndexRoute,
  ExpedientesIndexRoute: ExpedientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
